### ISSUE TITLE
<&sfsu hook:> hook is broken with new powershell

### ISSUE THREAD

**Issue by Kamek437** [winpax/sfsu#488] opened 2023-12-28 22:27 UTC
## Describe the bug
Invoke-Expression (&sfsu hook)
```Invoke-Expression: Cannot convert 'System.Object[]' to the type 'System.String' required by parameter 'Command'. Specified method is not supported.```
I just updated and that's what I'm getting on pwsh load.

 $PSVersionTable.PSVersion 
Major  Minor  Patch  PreReleaseLabel BuildLabel
-----  -----  -----  --------------- ----------
7      4      0

## Steps to To Reproduce
Setup powershell hook is $profile. Not sure how to reproduce this. Invoke-Expression (&sfsu hook)

## Expected behavior
To Load as normal like it did yesterday.

## Version
1.8.0, Powershell 7.4.0, Windows 11

## Additional context
Worked yesterday so...?

**Comment by sammko** [comment] 2023-12-28 22:39
This is caused by https://github.com/jewlexx/sfsu/commit/ebc90aac3717abf08fed3cd60a018928a8f5e954#diff-9ec516944f80af910aeed530b6f861195efe35da305d167e2ebf2eab62f183aaR45-R46, the type of `&sfsu hook` is now a string array instead of a string. I used `Invoke-Expression (&sfsu hook | Out-String)` instead.

**Comment by jewlexx** [comment] 2023-12-29 00:55
It looks like PowerShell didn't like the helper comments I added for some reason.

This should be fixed after #489

**Closed as completed** 2023-12-29 01:01 UTC
Labels: bug
