### ISSUE TITLE
<scoop status:> break when using latest version

### ISSUE THREAD

**Issue by NotAsea** [winpax/sfsu#639] opened 2024-04-18 12:15 UTC
## Describe the bug

after update sfsu the regular `scoop status` break:

```cmd
> scoop status
error: unexpected argument 'status' found

Usage: sfsu.exe status [OPTIONS]

For more information, try '--help'.
```

## Steps to To Reproduce

1. Go to powershell
2. type `scoop status`
3. See error

## Expected behavior
calling sfsu directly work
```cmd
>sfsu status
Scoop app is up to date.
Bucket(s) are out of date. Run `scoop update` to get the latest changes.
```
but break when call from scoop, maybe something happend with sfsu hook
## Version

1.10.2

**Comment by NotAsea** [comment] 2024-04-18 12:18
for more context passing empty string denote by `''` or `""` work
```cmd
> scoop status ''
Scoop app is up to date.
All buckets up to date.
All packages are okay and up to date.
```
I dont know look like intentional

**Comment by jewlexx** [comment] 2024-04-18 15:28
Duplicate of #638

**Closed as not planned by jewlexx** 2024-04-18 15:28 UTC
Labels: bug, duplicate
